from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = ROOT / "vendor" / "timeblock-assistant" / "SOURCE_LOCK.json"
EXPECTED_SOURCE_SHA = "d2fe8f79987e678387275b0c4b769c1623057f2b"
EXPECTED_SOURCE_COUNT = 222
EXPECTED_DESTINATION_COUNT = 436


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _fail(message: str) -> int:
    print(f"ERROR: {message}", file=sys.stderr)
    return 1


def main() -> int:
    try:
        lock = json.loads(LOCK_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        return _fail(f"Assistant source lock cannot be read: {exc}")

    if lock.get("source_repo") != "Panjiaphu/fumap-bot-life":
        return _fail("Assistant source repository identity is invalid.")
    if lock.get("source_sha") != EXPECTED_SOURCE_SHA:
        return _fail("Assistant source SHA does not match the release pin.")
    if lock.get("sync_version") != 4:
        return _fail("Assistant source lock was not generated by sync version 4.")
    if lock.get("runtime_network_source") is not False:
        return _fail("Assistant runtime must not load its canonical source over the network.")
    if lock.get("source_extraction") != {
        "mode": "git_object_database",
        "working_tree_filters_applied": False,
    }:
        return _fail("Assistant source bytes were not extracted from the pinned Git objects.")

    source_paths = lock.get("source_paths")
    source_hashes = lock.get("source_hashes")
    entries = lock.get("entries")
    if not isinstance(source_paths, list) or len(source_paths) != EXPECTED_SOURCE_COUNT:
        return _fail("Assistant source path inventory is incomplete.")
    if not isinstance(source_hashes, dict) or len(source_hashes) != EXPECTED_SOURCE_COUNT:
        return _fail("Assistant source hash inventory is incomplete.")
    if not isinstance(entries, list) or len(entries) != EXPECTED_DESTINATION_COUNT:
        return _fail("Assistant destination inventory is incomplete.")

    seen_destinations: set[str] = set()
    for entry in entries:
        if not isinstance(entry, dict):
            return _fail("Assistant lock contains a malformed destination entry.")
        source_path = str(entry.get("source_path") or "")
        destination_path = str(entry.get("destination_path") or "")
        expected_hash = str(source_hashes.get(source_path) or "")
        if source_path not in source_paths or len(expected_hash) != 64:
            return _fail(f"Assistant source hash is invalid: {source_path}")
        if destination_path in seen_destinations:
            return _fail(f"Assistant destination is duplicated: {destination_path}")
        seen_destinations.add(destination_path)
        destination = (ROOT / destination_path).resolve()
        if not destination.is_relative_to(ROOT.resolve()):
            return _fail(f"Assistant destination escapes the repository: {destination_path}")
        if not destination_path.startswith(
            ("vendor/timeblock-assistant/", "app/static/", "app/translations/")
        ):
            return _fail(f"Assistant destination is outside the allowlist: {destination_path}")
        if entry.get("adaptation_class") != "EXACT_VENDOR":
            return _fail(f"Assistant destination is not exact: {destination_path}")
        if entry.get("source_sha256") != expected_hash or entry.get("destination_sha256") != expected_hash:
            return _fail(f"Assistant lock hashes disagree: {destination_path}")
        if not destination.is_file() or _sha256(destination) != expected_hash:
            return _fail(f"Assistant destination hash mismatch: {destination_path}")

    print(
        "Assistant source lock verified: "
        f"{EXPECTED_SOURCE_COUNT} source files / {EXPECTED_DESTINATION_COUNT} destinations."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
